services:
  backend:
    build:
      context: ./skateparadise
      dockerfile: backend/Dockerfile.backend
    volumes:
      - ./skateparadise:/app
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    working_dir: /app
    env_file:
      - ./skateparadise/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    working_dir: /app
    depends_on:
      - backend