# Generated by Django 5.2 on 2025-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='img')),
                ('category', models.CharField(blank=True, choices=[('Boards', 'BOARDS'), ('Trucks', 'TRUCKS'), ('Grips', 'GRIPS'), ('Roues', 'ROUES'), ('Sweats', 'SWEATS'), ('vestes', 'VESTES'), ('Chaussures', 'CHAUSSURES'), ('Bonnets', 'BONNETS'), ('Ceintures', 'CEINTURES')], max_length=191, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
