# Generated by Django 5.2 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
