# Generated by Django 5.2.1 on 2025-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0006_alter_order_payment_method_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Boards', 'BOARDS'), ('Trucks', 'TRUCKS'), ('Grips', 'GRIPS'), ('Roues', 'ROUES'), ('Sweats', 'SWEATS'), ('vestes', 'VESTES'), ('Chaussures', 'CHAUSSURES'), ('Bonnets', 'BONNETS'), ('Ceintures', 'CEINTURES')], default='Boards', max_length=50),
        ),
    ]
