# Generated by Django 5.2.1 on 2025-05-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Boards', 'BOARDS'), ('Trucks', 'TRUCKS'), ('Grips', 'GRIPS'), ('Roues', 'ROUES'), ('Sweats', 'SWEATS'), ('Chaussures', 'CHAUSSURES'), ('Bonnets', 'BONNETS'), ('Ceintures', 'CEINTURES')], default='Boards', max_length=50),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, help_text="Code de session pour identifier les favoris d'un utilisateur anonyme.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='sp_shop.product')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('session_code', 'product')},
            },
        ),
    ]
