# Generated by Django 5.2 on 2025-04-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0008_remove_order_status_order_updated_at_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_code',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sp_shop.cart'),
        ),
    ]
