# Generated by Django 5.2 on 2025-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte Bancaire'), ('paypal', 'PayPal')], default='card', max_length=20),
        ),
    ]
