# Generated by Django 5.2.1 on 2025-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0011_remove_product_sizes_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('completed', 'Expédié'), ('livrée', 'Livrée')], default='attente', max_length=20),
        ),
    ]
