# Generated by Django 5.2.1 on 2025-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('expédié', 'Expédié'), ('livrée', 'Livrée')], default='attente', max_length=20),
        ),
    ]
