# Generated by Django 5.2.1 on 2025-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0015_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
