# Generated by Django 5.2.1 on 2025-06-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0017_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='sp_shop.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
