# Generated by Django 5.2.1 on 2025-05-18 11:00

import sp_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0017_cart_items_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default=sp_shop.models.generate_tracking_code, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte Bancaire'), ('paypal', 'PayPal')], default='', max_length=20),
        ),
    ]
