# Generated by Django 5.2.1 on 2025-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0018_order_tracking_code_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Exemple: 8.25,8.375', max_length=255, null=True),
        ),
    ]
