# Generated by Django 5.2.1 on 2025-06-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_shop', '0020_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, help_text='Taille sélectionnée pour ce produit (ex: S, M, L, 42, etc.)', max_length=10, null=True),
        ),
    ]
