# Dockerfile.backend
FROM python:3.11-slim

# Installer les dépendances système
RUN apt-get update && apt-get install -y build-essential

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r backend/requirements.txt

EXPOSE 8001

CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]